// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA68NGy-UqU4HkUJvH7ySN0ufWjKgiYqsQ',
    appId: '1:1037848093759:web:10e3556c515b4547bb448a',
    messagingSenderId: '1037848093759',
    projectId: 'lab09-da7e4',
    authDomain: 'lab09-da7e4.firebaseapp.com',
    storageBucket: 'lab09-da7e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bjdtN2r83d-mYjfk1zygJPNLAYJ5IBM',
    appId: '1:1037848093759:android:a489b1c9b4d796f1bb448a',
    messagingSenderId: '1037848093759',
    projectId: 'lab09-da7e4',
    storageBucket: 'lab09-da7e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYqTVpTMUSVJKJgO9q-fLGpab2FQLVTY',
    appId: '1:1037848093759:ios:2611c5c30a20d7b8bb448a',
    messagingSenderId: '1037848093759',
    projectId: 'lab09-da7e4',
    storageBucket: 'lab09-da7e4.appspot.com',
    iosClientId: '1037848093759-ihll7r86o7o24h1ti12u8ntntd6n3gf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYqTVpTMUSVJKJgO9q-fLGpab2FQLVTY',
    appId: '1:1037848093759:ios:2611c5c30a20d7b8bb448a',
    messagingSenderId: '1037848093759',
    projectId: 'lab09-da7e4',
    storageBucket: 'lab09-da7e4.appspot.com',
    iosClientId: '1037848093759-ihll7r86o7o24h1ti12u8ntntd6n3gf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );
}
